rules:
  - action: drop
    protocol: tcp
    port: 0-1023
    source: 0.0.0.0/0

  - action: drop
    protocol: udp
    port: 0-1023
    source: 0.0.0.0/0

  - action: drop
    protocol: tcp
    port: 80
    source: 192.168.0.0/16

  - action: drop
    protocol: udp
    port: 53
    source: 192.168.0.0/16

  - action: drop
    protocol: tcp
    port: 22
    source: 192.168.0.0/16

  - action: drop
    protocol: tcp
    port: 443
    source: 192.168.0.0/16
